name: Generate dependency modules
on: [push]
jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: aws/aws-cdk
          ref: v1.46.0
