name: Get AWS CDK Release
description: GitHub Action that retrieves the Node.js packages from an AWS CDK release by tag
inputs:
  token:
    description: "Your GitHub token"
    required: true
  tag:
    description: "The tag of the AWS CDK release you woulld like to retreive"
    required: true
outputs:
  time:
    description: "The time we greeted you"
runs:
  using: "node12"
  main: "index.js"
